CONFIDENCE_THRESHOLD  = 0.8
NUM_OBJECTS           = 3
RANDOM_SEED           = 42
SIMULATION_DT         = 0.05
DISTANCE_SCALE        = 0.25   # normalized [0,1]; 25% off-axis deviation → likelihood ≈ 0.37
DIRECTION_WEIGHT      = 0.8    # reduced from 2.0; prevents rapid collapse at 30fps webcam
LOCK_MIN_TRAVEL_PX    = 200     # cumulative travel required before any lock is allowed
LOCK_CONFIRM_FRAMES   = 10     # consecutive frames above CONFIDENCE_THRESHOLD before lock fires
ADAPTATION_GAIN       = 0.1
WEBCAM_INDEX          = 0
SMOOTHING_ALPHA       = 0.35
FLASK_PORT            = 5001
PYBULLET_RENDER_W = 400    # width of PyBullet camera render in pixels
PYBULLET_RENDER_H = 400    # height of PyBullet camera render in pixels
ROBOT_D_SCALE = 0.85       # robot arm arrives at D_remaining * ROBOT_D_SCALE seconds
